groups:

  public:
    displayName: Public screens
    autoOn:      08:00:00
    autoOff:     18:15:00

  private:
    displayName: Private screens
    autoOn:      08:00:00
    autoOff:     18:15:00


screens:

  screen1:
    displayName: Office
    host:        http://kodi:Southpark6279@10.0.0.7:8080
    groups:
      - public

  screen2:
    displayName: Bedroom
    host:        http://kodi:Southpark6279@10.0.0.176:8080
    groups:
      - private

  screen3:
    displayName: Living Room
    host:        http://kodi:Southpark6279@10.0.0.170:8080
    groups:
      - public

locations:

  - social: smb://screen-srv/social/images/
  - stats:  smb://screen-srv/stats/images/
