<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>KodiKontroller</title>
        <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
        <style>
            body {
                margin: 50px 0 0 0;
                padding: 0;
                width: 100%;
                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
                text-align: center;
                color: #aaa;
                font-size: 18px;
            }

            h1 {
                color: #719e40;
                letter-spacing: -3px;
                font-family: 'Lato', sans-serif;
                font-size: 100px;
                font-weight: 200;
                margin-bottom: 0;
            }
            table {
                margin: 1em auto;
            }
            td {
                padding: .5em;
            }
        </style>
    </head>
    <body>
        <h1>Kodi Kontroller</h1>
        <div>Multi-screen management</div>
        <h2>Currently registered screens</h2>
        <p>(Sample output)</p>
        <table>
            <tr>
                <th>Screen name</th>
                <th>Group</th>
                <th>Status</th>
            </tr>
            <tr>
                <td>South wing reception</td>
                <td>Public</td>
                <td>Online</td>
            </tr>
            <tr>
                <td>The Hub</td>
                <td>Public</td>
                <td>Online</td>
            </tr>
            <tr>
                <td>North wing breakfast bar</td>
                <td>Public</td>
                <td>Offline</td>
            </tr>
            <tr>
                <td>Technical Solutions</td>
                <td>Tech</td>
                <td>Online</td>
            </tr>
        </table>
    </body>
</html>
