groups:

  - name:        public
    displayName: Public screens
    autoOn:      08:00:00
    autoOff:     18:15:00

  - name:        tech
    displayName: Technical Solutions
    autoOn:      08:00:00
    autoOff:     18:15:00


screens:

  - name:        screen1
    displayName: Screen One
    host:        https://user:password@scrn1.test.fake:1234
    group:       public

  - name:        screen2
    displayName: Screen Two
    host:        https://user:password@scrn2.test.fake:1234
    group:       public

  - name:        screen3
    displayName: Screen Three
    host:        https://user:password@scrn3.test.fake:1234
    group:       tech

  - name:        screen4
    displayName: Screen Four
    host:        https://user:password@scrn4.test.fake:1234
    group:       tech


locations:

  - social: smb://screen-srv/social/images/
  - stats:  smb://screen-srv/stats/images/
