groups:

  public:
    displayName: Public screens
    autoOn:      08:00:00
    autoOff:     18:15:00

  private:
    displayName: Private screens
    autoOn:      08:00:00
    autoOff:     18:15:00


screens:

  screen1:
    displayName: Screen One
    host:        https://user:password@scrn1.test.fake:1234
    groups:
      - public

  screen2:
    displayName: Screen Two
    host:        https://user:password@scrn2.test.fake:1234
    groups:
      - private

  screen3:
    displayName: Screen Three
    host:        https://user:password@scrn3.test.fake:1234
    groups:
      - public

  screen4:
    displayName: Screen Four
    host:        https://user:password@scrn4.test.fake:1234
    groups:
      - public
      - private


locations:

  - social: smb://screen-srv/social/images/
  - stats:  smb://screen-srv/stats/images/
